language: node_js
node_js:
    - "6.10"
    - "8.9"
    - latest

addons:
  codeclimate:
    repo_token:
      - secure: CODECLIMATE_REPO_TOKEN

install:
    - npm install
    - npm install -g codecov
script:
    - npm test
    - npm run coverage
after_success:
    - codecov
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
